on:
  push:
    paths:
      - "11-04-99.zip"

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: unzip -o 11-04-99.zip -d .

      - run: rm 11-04-99.zip

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Extract ZIP" || exit 0
          git push
