name: Extract ZIP

on:
  push:
    branches:
      - main
    paths:
      - "11-04-99.zip"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: unzip -o "11-04-99.zip" -d .

      - name: Remove ZIP
        run: rm "11-04-99.zip"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Extract ZIP"
          git push
